name: Start-Pulumi-with-EC2 # pulumi.get_project()
description: NA
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
