name: DevDeploy
on: 
  pull_request: 
    branches: 
      - "dev"

jobs: 
  DevPreview: 
    name: Dev Preview 
    runs-on: ubuntu-24.04
    permissions: 
      id-token: write 
      contents: read 
      pull-requests: write 
    
    steps: 
      - uses: actions/checkout@4

      - name: Configure AWS credentials OIDC 
        uses: aws-actions/configure-aws-credentials@v4 
        with: 
          role-to-assume: ${{ secrets.ActionsRoleArn  }}
          aws-region: ap-southeast-1
      
      - name: Zip sources 
        run: | 
          rm -rf build/ 
          mkdir build 
          find . -exec touch -t "$(git ls-files -z . | \
          xargs -0 -n1 -I{} -- git log -1 --date=format:"%Y%m%d%H%M" --format="%ad" '{}' | \
          sort -r | head -n 1)" '{}' +
          zip -rq -X -9 -A --compression-method deflate build/lambda.zip *.py
      
      - uses: pulumi/action@v5 
        with: 
          command: preview 
          stack-name: veraz00/dev 
          work-dir: infra 
          commnet-on-pr: true  
# When you create a PR in your GitHub repository, Pulumi will detect the change and trigger a deployment.
# After the deployment completes, Pulumi will comment on the PR with the results of the deployment, including any errors or warnings.


          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GIT_SHA: ${{ github.sha }}
